### ISSUE TITLE
Send Token Confirmation Screen

### ISSUE THREAD

**Issue by cswenor** [temptemp3/arc-200#10]
We need some kind of confirmation that I just sent, and also a confirmation that the blockchain received and processed the transaction.

**Comment by temptemp3** [comment]
https://github.com/temptemp3/arc-200/assets/23183451/b0e00232-8109-4cd3-9b5f-2ea911c84850

**Comment by temptemp3** [comment]
Added progress while waiting for signature and confirmation. Once transaction is confirmed a notification should appear.

**Comment by temptemp3** [comment]
Just pushing this. Give it a minute or two.

**Comment by cswenor** [comment]
This works, but it probably should close the send popup.

**Comment by temptemp3** [comment]
Now closes popup

**Comment by temptemp3** [comment]
Deploying

**Comment by cswenor** [comment]
All good!
