### ISSUE TITLE
Receiving Error when sending with Defly

### ISSUE THREAD

**Issue by cswenor** [temptemp3/arc-200#11]
Tried to send Asset 249906631. In the console I get this error:
![image](https://github.com/temptemp3/arc-200/assets/647451/f6889e62-6ba8-4d15-805a-ad79a20356f8)

**Comment by cswenor** [comment]
This error happens when I push any button in the app.

**Comment by temptemp3** [comment]
The app bar originally did some queries for ASA these were removed. Should not see any more.
Going to try sending with Defly on my end.

**Comment by temptemp3** [comment]
Was able to send with Defly using Pera

**Comment by temptemp3** [comment]
Defly transfer should work. It takes a little setting to make sure testnet is enabled and the right account is selected.

**Comment by temptemp3** [comment]
Deploying new build right now (1-2 minutes ready)

**Comment by cswenor** [comment]
![image](https://github.com/temptemp3/arc-200/assets/647451/4e1bf386-c337-453c-8b6a-b3e116d34825)
Stilll happening

**Comment by temptemp3** [comment]
Asset fetching does not appear in wallet page

**Comment by temptemp3** [comment]
<img width="1513" alt="Screen Shot 2023-06-27 at 17 27 38" src="https://github.com/temptemp3/arc-200/assets/23183451/d220ad68-44b4-4bdd-81e0-1c5955b01fb6">

**Comment by temptemp3** [comment]
But does still appear in send dialog

**Comment by temptemp3** [comment]
Removed cause of asset fetching, some unused component

**Comment by cswenor** [comment]
Haha still happening when I go to the send asset dialog. 
![image](https://github.com/temptemp3/arc-200/assets/647451/72cf3516-5646-4432-8ea1-bb73f9df0ed7)

**Comment by temptemp3** [comment]
Giving it another go on my end

**Comment by temptemp3** [comment]
I had a look around but was not able to replicate the issue. I suspect that the update was not in effect at the time it was last checked.

**Comment by cswenor** [comment]
All good!
