### ISSUE TITLE
Add commas to balance on the balances screen.

### ISSUE THREAD

**Issue by cswenor** [temptemp3/arc-200#13]
Without commas it's hard to see how much I have.

**Comment by temptemp3** [comment]
Need account with balance that would require commas. Commas are for display purposes. Most users would prefer to have commas included. Noted.

**Comment by temptemp3** [comment]
<img width="845" alt="Screen Shot 2023-06-27 at 14 10 52" src="https://github.com/temptemp3/arc-200/assets/23183451/9d9bd9ed-135e-40af-8b4e-e0aff683237a">
<img width="844" alt="Screen Shot 2023-06-27 at 14 10 23" src="https://github.com/temptemp3/arc-200/assets/23183451/38c7fa68-6cdf-42b6-b9bc-28ab4656975f">

**Comment by temptemp3** [comment]
@cswenor this one should be ready to review in 3-5 minutes

**Comment by temptemp3** [comment]
<img width="1222" alt="Screen Shot 2023-06-27 at 15 04 35" src="https://github.com/temptemp3/arc-200/assets/23183451/05f4b7d9-eb78-42bb-8ffb-cd29cd1cc1d3">

**Comment by temptemp3** [comment]
Followed up with some improvements. Display should included commas for tokens with decimals between 0 and 19

**Comment by temptemp3** [comment]
Here are some tokens
https://gist.github.com/temptemp3/d2e4a65e11076051fe697a4e1d0e5a4c
