### ISSUE TITLE
Upgrade to the latest version of use-wallet.

### ISSUE THREAD

**Issue by cswenor** [temptemp3/arc-200#14]
https://twitter.com/NFDomains/status/1673836625602699269

**Comment by temptemp3** [comment]
Should be good to go

**Comment by temptemp3** [comment]
FYI, Wallet connect v2 and Exudus don't work yet

**Comment by cswenor** [comment]
wallet connect v2 don't work yet? Wsan't the announcement today that they now do?

**Comment by temptemp3** [comment]
It should work. I just have to figure out how to initialize it. Details
<img width="681" alt="Screen Shot 2023-06-28 at 10 38 50" src="https://github.com/temptemp3/arc-200/assets/23183451/185cc29a-a101-4287-b8cd-ae2c9078d6af">
I'll have another pass soon. Hopefully it just works.

**Comment by temptemp3** [comment]
Probably okay for now since WalletConnect on app.testnet.nf.domains
isn't working yet. I'm working on getting a providerId from WalletConnect. We'll see how it goes.

**Comment by temptemp3** [comment]
I think the best bet here would be to go to the wallet connect v2 docs and work on a connects solution outside of txnslabs, then backtrack to what is missing. Note that in the dapp, txnslab-use-wallet is only used to connect the wallet and get the address. It also sets localstorage keys we will need in reach to use stdlib.connectAccount({addr})

**Comment by temptemp3** [comment]
May add back legacy wallets MyAlgo and possibly Algosigner

**Comment by cswenor** [comment]
Nah, you should keep them out. No reason to add them at this point since they are both abandoned projects.

**Comment by cswenor** [comment]
This is good.
