### ISSUE TITLE
Implement Mint Page

### ISSUE THREAD

**Issue by cswenor** [temptemp3/arc-200#16]
We need an easy way to mint new tokens.

**Comment by temptemp3** [comment]
Location:
`/#/mint`

**Comment by temptemp3** [comment]
https://github.com/temptemp3/arc-200/assets/23183451/3e2fffcb-e8ff-4fda-ba41-52ede84975d9

**Comment by temptemp3** [comment]
Almost done. Just need to add a spinner similar to the send form.

**Comment by temptemp3** [comment]
https://github.com/temptemp3/arc-200/assets/23183451/7999a3d6-70a6-45ae-997c-e0765008f16d

**Comment by temptemp3** [comment]
Ready

**Comment by cswenor** [comment]
On Error it deletes all things in the text box, and doesn't display an error. 

The error that happened is that I just cancelled the transaction on my wallet.

Also when I went through and minted the token this is what it looked like. 
![image](https://github.com/temptemp3/arc-200/assets/647451/7e83940a-7a19-43ee-850a-7fb8c882549f)

I think we need to apply trimming to the entries.

**Comment by cswenor** [comment]
Yeah this happens every time now even without an error haha.

Maybe we should have a confirmation screen before the mint?

This is where you would just make clear what they are about to mint, before you confirm it.

**Comment by temptemp3** [comment]
Yes. Adding a confirmation screen is a good move. Will do. Thx!
Might also trim the padding so that those boxes don't appear. In most browser they don't appear but apparently yours does.

**Comment by temptemp3** [comment]
TODO
* Add confirmation step to mint page (1)
* Trim entries to eliminate padding
* On error, retain information for previous input screen, may depend on (1)

**Comment by temptemp3** [comment]
> Trim entries to eliminate padding
Done

**Comment by temptemp3** [comment]
> On error, retain information for previous input screen, may depend on (1)

Done

**Comment by temptemp3** [comment]
https://github.com/temptemp3/arc-200/assets/23183451/3040edf0-678c-4e29-b437-86dabbfc45d2

**Comment by temptemp3** [comment]
Adding confirmation step before Mint

**Comment by cswenor** [comment]
Awesome!
