### ISSUE TITLE
Mobile Resizing

### ISSUE THREAD

**Issue by cswenor** [temptemp3/arc-200#18]
Ok mobile the screen zoom should be to fit screen. Right now you have to pinch out to make sure the screen fits.

**Comment by temptemp3** [comment]
There is a good chance you are right. Back to the drawing board on the responsive design. I'll have a look. Thx!

**Comment by temptemp3** [comment]
I made some changes over the weekend. It look okay on my iPhone SE. Would you mind having another peek? Thx!

**Comment by cswenor** [comment]
Looks good!
