### ISSUE TITLE
Missing bottom bar on the token screens

### ISSUE THREAD

**Issue by cswenor** [temptemp3/arc-200#19]
When you click into the token screens we lose the bottom bar. Also, if you don't have your wallet connected on those screens it doesn't tell you to connect it.

**Comment by temptemp3** [comment]
I purposely left these out but should fix. There are no issues reading information without a wallet connected. Will do. Thx!

**Comment by temptemp3** [comment]
<img width="1149" alt="Screen Shot 2023-07-01 at 0 44 08" src="https://github.com/temptemp3/arc-200/assets/23183451/abb839c1-85b3-40f6-a942-6a2e35f72e80">

Added home button and bottom bar appears on bottom of token screens

**Comment by cswenor** [comment]
The bottom bar should be opaque. It being transparent makes it hard to read when things are behind it.

**Comment by temptemp3** [comment]
![Screen Shot 2023-07-01 at 9 32 01](https://github.com/temptemp3/arc-200/assets/23183451/c30b3522-46e1-435f-8377-74dfffd4a13e)
![Screen Shot 2023-07-01 at 9 31 40](https://github.com/temptemp3/arc-200/assets/23183451/ee9840f0-b9cb-45e0-a613-9fb436ca60b2)

**Comment by temptemp3** [comment]
Ready

**Comment by cswenor** [comment]
Good to go!
