### ISSUE TITLE
Change App ID to just ID

### ISSUE THREAD

**Issue by cswenor** [temptemp3/arc-200#2]
People won't understand what an App ID is. We can just call it ID.

We will probably hide this in a future design, but for now just call it ID.

https://temptemp3.github.io/arc200.algo.xyz/

**Comment by temptemp3** [comment]
Done

**Comment by temptemp3** [comment]
<img width="1788" alt="Screen Shot 2023-06-28 at 0 37 00" src="https://github.com/temptemp3/arc-200/assets/23183451/d716a404-6e84-4458-b1b9-b15eb34089de">

**Comment by temptemp3** [comment]
Done

**Comment by cswenor** [comment]
Approved
