### ISSUE TITLE
Can't get the server to run.

### ISSUE THREAD

**Issue by cswenor** [temptemp3/arc-200#21]
1) Only one of these files should exist
![image](https://github.com/temptemp3/arc-200/assets/647451/96e7758a-d1ef-476c-a24f-d412196ee7de)

I went with Yarn and it warned me:
![image](https://github.com/temptemp3/arc-200/assets/647451/0427f272-48a9-4bf8-9882-732bc4e25918)

Afterwards, I run npm start and get this error:
![image](https://github.com/temptemp3/arc-200/assets/647451/ece04b27-af61-46e5-85cb-77783e787355)

**Comment by temptemp3** [comment]
@scottbolasevich  and I worked through this one here

https://github.com/temptemp3/arc-200/tree/fix-build

I just want to make sure it all works on my machine. It seems to works on Scott's.

TODO

- [ ] Test start/build on Mac
- [ ] Test start/build on Windows

**Comment by temptemp3** [comment]
https://github.com/temptemp3/arc-200/pull/22

**Comment by temptemp3** [comment]
@cswenor could you relay this one back for testing. Thx!

**Comment by cswenor** [comment]
/app/app-sandbox still has both lock files.

**Comment by cswenor** [comment]
![image](https://github.com/temptemp3/arc-200/assets/647451/1b136e50-e881-414b-81ce-16dd6b2b55dd)

Page renders now, but when trying to click on the wallets the page just reloads

**Comment by temptemp3** [comment]
Let me see

**Comment by temptemp3** [comment]
I should add some instructions to use yarn in the quickstart

**Comment by temptemp3** [comment]
Pls go through the step of remove node_modules if you were previously on the main branch before the update
`rm -rvf node_modules ; yarn; yarn start`

**Comment by temptemp3** [comment]
I suspect it may be related when trying to click wallets but the page reloads

**Comment by temptemp3** [comment]
Just to be on the safe side clear localStorage and hard refresh. Thx!

**Comment by cswenor** [comment]
the double lock file still exists.

**Comment by temptemp3** [comment]
Let me see. Maybe I got stuck.

**Comment by temptemp3** [comment]
Fixed. Thanks for pointing it out
https://github.com/temptemp3/arc-200/commit/fdb3419ddd64a33c592b95d7ea3e10c442094411

**Comment by cswenor** [comment]
Should be good to go now.
