### ISSUE TITLE
Wrong Link in the About section in Github

### ISSUE THREAD

**Issue by cswenor** [temptemp3/arc-200#23]
![image](https://github.com/temptemp3/arc-200/assets/647451/edc7ce62-66d7-4a09-afe7-0f361dee1367)

This should point to https://arc200.algodrop.net/

**Comment by temptemp3** [comment]
Done

**Comment by temptemp3** [comment]
Done ; )
* Update about page link to  https://arc200.algodrop.net/
* Added open-source tags

Any other tags?

**Comment by cswenor** [comment]
Good to go
