### ISSUE TITLE
Customizable Nodes

### ISSUE THREAD

**Issue by cswenor** [temptemp3/arc-200#24]
You should make it so that the network/nodes you communicate with are customizable. 

This should be in a settings dropdown it should be:

- Voi Disabled
- Algorand Disabled
- Algorand (Testnet)
- Custom

Custom should give you a pop up where you can just input the address to the node and the indexer of your choice.

**Comment by temptemp3** [comment]
<img width="1199" alt="Screen Shot 2023-07-02 at 15 40 03" src="https://github.com/temptemp3/arc-200/assets/23183451/f01dfd62-1f4d-41af-8313-5cbe36abecf4">

* HumbleSwap network provider selector
** Note this is a network provider selector where the network is constant

Customizable nodes will entail selecting the pair

network, provider

**Comment by temptemp3** [comment]
Propose setting up a `/#/config` page to act until future design changes

**Comment by temptemp3** [comment]
Custom node Algorand (Testnet)

Node: `https://testnet-api.algonode.cloud`. 
Indexer: `https://testnet-idx.algonode.cloud`

**Comment by cswenor** [comment]
Not sure that I understand this, but I'll see when you build it:

** Note this is a network provider selector where the network is constant
Customizable nodes will entail selecting the pair

network, provider

**Comment by temptemp3** [comment]
Config page
https://arc200.algodrop.net/#/config

**Comment by temptemp3** [comment]
(1) Select node
(2) Click update button *does not have popup saying that "node updated" yet
(3) Go home

**Comment by temptemp3** [comment]
- [ ] Add gear link to app bar

**Comment by cswenor** [comment]
Works great!
