### ISSUE TITLE
Contract update i

### ISSUE THREAD

**Issue by temptemp3** [temptemp3/arc-200#25]
Updates

* **Add network seconds** to events 
Reasoning: Need network seconds in event to show datatimes in token info pages 
* Check that decimals are same as ASA (0-19)   
Reasoning: Need to make sure that ARC200 tokens are compatible with ASAs with respect to decimals
* Rename managerAddress -> manager
Reasoning: manager is less questionable than managerAddress

Plan

After completion of contract update and test script, the new contract will replace the existing contract. The app using the previous version of the contract will be left availabled at https://arc200v0.algodrop.net/

## Add network seconds to events

There are 2 event types emitted by the contract.

```
  const E = Events({
    Transfer: [Address, Address, UInt],
    Approval: [Address, Address, UInt],
  });
  ```
  
Transfer emits the from to address and amount.

Propose change to

```
Transfer: [Address, Address, UInt, UInt],
```

The additional UInt will contain the networks seconds at the time the transaction block was confirmed.

Similarly, Approval have a similar update.

## Check that decimals are same as ASA (0-19)   

```
const MAX_DECIMALS = 19; // same as AS
...
      check(
        meta.decimals < MAX_DECIMALS,
        "ARC200: Decimals must be less than 19"
      );
```

**Comment by temptemp3** [comment]
@cswenor I finished the update we discuss. At the very least I migrated the old arc200 tokens to the new contract.
Feel free to close this issue. Thx!

**Comment by cswenor** [comment]
Approved!
