### ISSUE TITLE
Remove the initial box from the Holders list.

### ISSUE THREAD

**Issue by cswenor** [temptemp3/arc-200#27]
![image](https://github.com/temptemp3/arc-200/assets/647451/bb5d54b2-b898-4459-b40e-49aa2c2e3a9d)

**Comment by temptemp3** [comment]
<img width="1268" alt="Screen Shot 2023-07-02 at 8 27 25" src="https://github.com/temptemp3/arc-200/assets/23183451/cdac1065-3394-4dd8-9bf2-7ce50ab6fcf2">

**Comment by temptemp3** [comment]
Done. The token zero address will not be displayed in holdlers table

**Comment by temptemp3** [comment]
Pls clear localStorage. Thx

**Comment by temptemp3** [comment]
Ready

**Comment by cswenor** [comment]
Looks good!
