### ISSUE TITLE
Pera web connects ok but does not call when minting

### ISSUE THREAD

**Issue by dlightdlight** [temptemp3/arc-200#29]
will connect and display when connecting to pera web but when you go to mint it calls wallet connect.
once disconnected and reconnected to pera mobile the minting works fine

**Comment by temptemp3** [comment]
I see. So there is an issue using pera web. Got it. Makes sense. In the mean time pls use pera mobile if you have to. Thx!

**Comment by temptemp3** [comment]
Was able to replicate the issue. Looking into. Should fix soon.

**Comment by temptemp3** [comment]
Looks like this one will require some more digging to attack the root cause and come up with a work around. Allow me to come back to this one. In the mean time, if using pera, use pera mobile. Issues with pera web will be resolved soon. Thx!

**Comment by temptemp3** [comment]
PeraWallet localStorage keys
PeraWallet.Wallet:Object
.type pera-wallet ... PeraWallet Mobile
.type pera-wallet-web ... PeraWallet Web

**Comment by temptemp3** [comment]
https://github.com/reach-sh/reach-lang/issues/1548

**Comment by temptemp3** [comment]
https://github.com/reach-sh/reach-lang/blob/71ff35239e373ba7dca00604ee796be5362b4751/js/stdlib/ts/ALGO_MakePeraConnect.ts#L37

**Comment by temptemp3** [comment]
https://github.com/reach-sh/reach-lang/discussions/1547

**Comment by temptemp3** [comment]
@dlightdlight

**Comment by temptemp3** [comment]
<img width="1181" alt="Screen Shot 2023-07-03 at 21 29 12" src="https://github.com/temptemp3/arc-200/assets/23183451/1d796ec0-f825-43e2-b4f3-a407d4ba4eda">

<img width="1181" alt="Screen Shot 2023-07-03 at 21 29 18" src="https://github.com/temptemp3/arc-200/assets/23183451/f7165f52-ee18-49e3-8413-774dac69389e">

<img width="1181" alt="Screen Shot 2023-07-03 at 21 29 23" src="https://github.com/temptemp3/arc-200/assets/23183451/498ee069-2b16-43e7-87b0-da9a9f2fc7de">

**Comment by dlightdlight** [comment]
@temptemp3 you fixed it.
did you push the update yet as i still have the same error ?

**Comment by temptemp3** [comment]
> @temptemp3 you fixed it. did you push the update yet as i still have the same error ?

Yes, I did. Sorry please try again. Thanks!

**Comment by temptemp3** [comment]
Let me know if it works on your end

**Comment by dlightdlight** [comment]
checked and all fixed.  working as expected now.
