### ISSUE TITLE
Implement NFD

### ISSUE THREAD

**Issue by cswenor** [temptemp3/arc-200#3]
The send to field and also the wallet display at the bottom should show your NFD if you have one.

**Comment by temptemp3** [comment]
Here is a good example of (2)
https://flow.algo.surf/

**Comment by temptemp3** [comment]
@cswenor NFT display ready

**Comment by temptemp3** [comment]
https://github.com/temptemp3/arc-200/assets/23183451/eea63760-8568-4354-a6be-b5502b61cd10

**Comment by temptemp3** [comment]
Send with NFD ready

**Comment by temptemp3** [comment]
>  Form controls requiring address may lookup address via NFD

Just send page

**Comment by temptemp3** [comment]
Ready

**Comment by cswenor** [comment]
Sometimes it doesn't pick up the NFD even if it has one
![image](https://github.com/temptemp3/arc-200/assets/647451/bbd1aa3f-a0e2-4a7e-a759-c16b149077a9)

**Comment by temptemp3** [comment]
Yup. It should recover if the screen is reloaded. The way it works now is lazy, i.e. use what you have while doing work for the future in the hope of getting them all the next time. 
I'll see about having it be fixed without having to wait until next time.

**Comment by temptemp3** [comment]
Token info page updated

**Comment by temptemp3** [comment]
Transaction page updated

**Comment by temptemp3** [comment]
- [ ] Update app bard address display for nfd

**Comment by temptemp3** [comment]
Ready

**Comment by cswenor** [comment]
Haven't had an issue yet. I'll close it. :)
