### ISSUE TITLE
Implement Copy Wallet Address

### ISSUE THREAD

**Issue by cswenor** [temptemp3/arc-200#4]
Copy your wallet id to the clip board when you click the copy button.

**Comment by temptemp3** [comment]
<img width="1626" alt="Screen Shot 2023-06-28 at 0 38 23" src="https://github.com/temptemp3/arc-200/assets/23183451/d17b341a-2eda-4687-beca-36ad709ca69b">

**Comment by temptemp3** [comment]
Not yet implemented

**Comment by temptemp3** [comment]
<img width="1077" alt="Screen Shot 2023-06-28 at 10 31 50" src="https://github.com/temptemp3/arc-200/assets/23183451/e2c64c48-a7fd-40f2-afdb-cbf0032bce66">

**Comment by temptemp3** [comment]
Ready

**Comment by cswenor** [comment]
Perfect.
