### ISSUE TITLE
Transaction Page

### ISSUE THREAD

**Issue by cswenor** [temptemp3/arc-200#6]
You should be able to click on an individual token and see your transactions in that token. Both sent and received.

**Comment by temptemp3** [comment]
Added transactions page
/#/transaction/249906631

**Comment by cswenor** [comment]
I think your routing is broken. I'm getting the same issue as when looking for the meta data.
![image](https://github.com/temptemp3/arc-200/assets/647451/6263232d-0a34-4a09-b8ec-61df51763c90)

**Comment by temptemp3** [comment]
Same here
https://temptemp3.github.io/arc200.algo.xyz/#/transaction/249906631

**Comment by temptemp3** [comment]
More optimization to be done here like reusing txn information already fetched. Faster on the ms scale.
Also, if the user has the page open it could feed in new information realtime.
@cswenor Question: do we want timestamp information in the transactions table?
If so I might have to add that information to the events.

**Comment by temptemp3** [comment]
New domain it should be okay now
https://arc200.algodrop.net/

**Comment by cswenor** [comment]
This issue is to be able to view all of individual wallet transactions. To see where all the transactions that I was involved in.

**Comment by temptemp3** [comment]
It is similar to the token info page but shows transactions to and from the active account address.

**Comment by cswenor** [comment]
Have you implemented this and I missed it?

**Comment by temptemp3** [comment]
Going to revisit this with token info page

**Comment by temptemp3** [comment]
> Have you implemented this and I missed it?

Yes but I'll be sure to confirm before kicking it back to you

**Comment by temptemp3** [comment]
This has been implemented. I'll update the balances page so that it is easier to access both the token info page and transactions page.

**Comment by temptemp3** [comment]
Made some quick edits to the wiki adding locations in the app
https://github.com/temptemp3/arc-200/wiki

**Comment by temptemp3** [comment]
<img width="1676" alt="Screen Shot 2023-06-29 at 11 04 35" src="https://github.com/temptemp3/arc-200/assets/23183451/c1c2963f-20ec-474f-84ac-fa1b24066da6">

Here is the Token page (token info) that contains

- token metadata
- holders
- transactions (all)

**Comment by temptemp3** [comment]
<img width="874" alt="Screen Shot 2023-06-29 at 11 07 00" src="https://github.com/temptemp3/arc-200/assets/23183451/79dc898b-8eaa-4f96-b217-fa597c7ff9d8">

Here is the Transaction page (transactions for ARC200 token for connected wallet) that contains

- token metadat
- transactions (for 1 account)

**Comment by temptemp3** [comment]
Kicking it back to you @cswenor

**Comment by cswenor** [comment]
Looks good!
