### ISSUE TITLE
Token Info page

### ISSUE THREAD

**Issue by cswenor** [temptemp3/arc-200#7]
You should be able to click on the token to find out the meta data of that token.

**Comment by temptemp3** [comment]
<img width="875" alt="Screen Shot 2023-06-28 at 0 07 35" src="https://github.com/temptemp3/arc-200/assets/23183451/03bc6bca-2199-48f1-a2e1-8773c4976a0d">

**Comment by temptemp3** [comment]
Linked to page displaying metadata from balances page

**Comment by temptemp3** [comment]
Token info page may show all transactions

**Comment by temptemp3** [comment]
`/#/token/249906631`

**Comment by temptemp3** [comment]
Let me see

**Comment by temptemp3** [comment]
My bad it has to be this page
https://temptemp3.github.io/arc200.algo.xyz/#/token/249906631

**Comment by temptemp3** [comment]
More optimization to be done here like reusing txn information already fetched. Faster on the ms scale.
Also, if the user has the page open it could feed in new information realtime.
@cswenor Question: do we want timestamp information in the transactions table?
If so I might have to add that information to the events.

**Comment by cswenor** [comment]
Yes timestamp would be good. 

Also the links on the main wallet extension page send to the wrong place.

**Comment by cswenor** [comment]
This now works.
