### ISSUE TITLE
Bounty: Add ability to switch between wallets enabled by kibisis wallet (20k VIA)

### ISSUE THREAD

**Issue by temptemp3** [temptemp3/arc-200#74]
<img width="1155" alt="Screenshot 2023-12-22 at 9 37 59" src="https://github.com/temptemp3/arc-200/assets/23183451/86c2acd6-3a89-4f12-992f-262e19525446">

**Comment by cswenor** [comment]
10,000 VIA Bounty

**Comment by temptemp3** [comment]
Match 10k VIA Bounty

**Comment by temptemp3** [comment]
Done

**Comment by temptemp3** [comment]
Can also switch between A-Wallet and Kibisis
