### ISSUE TITLE
Send Screen: Balance

### ISSUE THREAD

**Issue by cswenor** [temptemp3/arc-200#9]
When you select a token it should display you balance of that token on that screen.

**Comment by cswenor** [comment]
This should also update the balance after a send.

**Comment by temptemp3** [comment]
Will do

**Comment by temptemp3** [comment]
https://github.com/temptemp3/arc-200/assets/23183451/34111bd5-9264-436b-8c81-06596caa2e0d

**Comment by temptemp3** [comment]
Balance now shown when selected

**Comment by temptemp3** [comment]
Deploying this right now

**Comment by cswenor** [comment]
Looks like you added a new error: 
![image](https://github.com/temptemp3/arc-200/assets/647451/cc530a8e-a91d-4abf-88e1-94faf10f2f54)

**Comment by cswenor** [comment]
Also needs commas in the balance.

**Comment by temptemp3** [comment]
Could you confirm this again. The last push just came into effect.

**Comment by temptemp3** [comment]
New issue patched up. Just need to add commas.

**Comment by temptemp3** [comment]
Added commas

**Comment by temptemp3** [comment]
Pushing right now. Available in a view minutes.

**Comment by cswenor** [comment]
All good!
